### ISSUE TITLE
Showing Error Something Went Wrong

### ISSUE THREAD

**Issue by NivinCNC** [devyuji/isave#1]
Showing Error Something Went Wrong while trying to download reels in heruko deployment

**Comment by devyuji** [comment]
Can you share me the Instagram URL.

**Comment by devyuji** [comment]
> Showing Error Something Went Wrong while trying to download reels in heruko deployment

Can you share me the Instagram URL.

**Comment by NivinCNC** [comment]
it worked in your website (isave.cc)
i deployed your isave respority in my heruko account
and when i try to download it through mine it shows error some thing went
wrong

**Comment by NivinCNC** [comment]
https://ignivin.herokuapp.com/
try downloading bro its shows error
i have attached a screen shot of this
![Screenshot_2021-09-19-11-24-26-339_com android chrome](https://user-images.githubusercontent.com/89772187/133917110-b6490e9b-bdf4-4417-992c-e8833c85c259.jpg)

**Comment by devyuji** [comment]
> https://ignivin.herokuapp.com/
> try downloading bro its shows error
> i have attached a screen shot of this
> ![Screenshot_2021-09-19-11-24-26-339_com android chrome](https://user-images.githubusercontent.com/89772187/133917110-b6490e9b-bdf4-4417-992c-e8833c85c259.jpg)
> 

Well only the front-end is open-source.
