### ISSUE TITLE
It is crashing after press download button

### ISSUE THREAD

**Issue by joaosilva-lp** [devyuji/isave#11]
Hi the website stop working when you try to download it gives an error.

I would like to know if you want my collaboration to do a version to run directly in terminal or if you can do it.
Cheers

**Comment by devyuji** [comment]
> Hi the website stop working when you try to download it gives an error.
> 
> I would like to know if you want my collaboration to do a version to run directly in terminal or if you can do it. Cheers

currently i am facing some error on server end. yeah sure lets have a chat about terminal
