### ISSUE TITLE
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

### ISSUE THREAD

**Issue by fdciabdul** [devyuji/isave#13]
i dont know why , when deploying to vercel , this is happen

**Comment by devyuji** [comment]
can you provide more information

**Comment by fdciabdul** [comment]
i try to deploy your repo to vercel

https://isave-9pmob0g8m-fdciabdul.vercel.app/

when i try to input the ig url , it says error , and the browser console says like above

**Comment by macros123** [comment]
Have same problem, i think it's because i didn't set process.env.API_URL What should i put here?

**Comment by fdciabdul** [comment]
I got it now @devyuji  didn't expose the api url because the backend isn't open source right ?
