### ISSUE TITLE
startup api give 503 error 

### ISSUE THREAD

**Issue by bhautiksavaj** [devyuji/isave#5]
startup api give 503 error 
https://www.isave.cc/_next/data/dW9SZZPVfQRUK_cLEB1yR/preview/bhavy_1208.json?username=bhavy_1208
also can't find the profile using [preview](https://www.isave.cc/preview)  tab

**Comment by devyuji** [comment]
I have looked into the issue. It seems someone is   making continuous request to the server that why server is giving you 503 error.

**Comment by bhautiksavaj** [comment]
can you share your env?
